"""Export a generated project: mesh, manifest, and the sheet inventory."""

import os
from . import geom2d as G

ENGINE_VERSION = "0.2.0"

MTL = """# ArchiAI generated materials
newmtl shell
Kd 0.72 0.74 0.76
Ks 0.18 0.18 0.18
Ns 32
d 1.0

newmtl wall
Kd 0.78 0.77 0.74
Ks 0.06 0.06 0.06
Ns 12
d 1.0

newmtl roof
Kd 0.55 0.57 0.58
Ks 0.10 0.10 0.10
Ns 20
d 1.0

newmtl slab
Kd 0.82 0.80 0.77
Ks 0.04 0.04 0.04
Ns 10
d 1.0
"""


def write_obj(mesh, path, name="building", mtl_name=None):
    """Wavefront OBJ from the engine's generic mesh, vertices deduplicated."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    index, verts = {}, []
    remap = []
    for v in mesh.v:
        k = (round(v[0], 4), round(v[1], 4), round(v[2], 4))
        i = index.get(k)
        if i is None:
            verts.append(k)
            i = index[k] = len(verts)
        remap.append(i)

    by_group = {}
    for gname, faces in mesh.groups.items():
        by_group[gname] = set(faces)
    ungrouped = set(range(len(mesh.f))) - set().union(*by_group.values()) if by_group else set(
        range(len(mesh.f)))
    if ungrouped:
        by_group.setdefault("shell", set()).update(ungrouped)

    with open(path, "w") as fh:
        fh.write("# %s -- generated by ArchiAI engine %s\n" % (name, ENGINE_VERSION))
        fh.write("# Units: metres. Z up. Origin at the plan centre, ground level.\n")
        if mtl_name:
            fh.write("mtllib %s\n" % mtl_name)
        for (x, y, z) in verts:
            fh.write("v %.4f %.4f %.4f\n" % (x, y, z))
        for gname, faces in by_group.items():
            if not faces:
                continue
            fh.write("g %s\no %s\n" % (gname, gname))
            if mtl_name:
                fh.write("usemtl %s\n" % (gname if gname in ("wall", "roof", "slab") else "shell"))
            for fi in sorted(faces):
                fh.write("f " + " ".join(str(remap[i]) for i in mesh.f[fi]) + "\n")
    return path, len(verts), len(mesh.f)


def write_mtl(path):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as fh:
        fh.write(MTL)
    return path


# ---------------------------------------------------------------------------
def cost_units(project, sheets):
    """Deterministic price of a generation, in whatever units the caller meters."""
    return 20 + 6 * len(sheets) + 2 * len(project.massing.levels)


def manifest(project, sheets, spec=None, model=None):
    """Everything the calling platform needs to persist and display."""
    m = project.massing
    levels = []
    for i, lv in enumerate(m.levels):
        fp = project.floorplans[i]
        rooms = [{"code": r.code, "name": r.name, "category": r.cat,
                  "area_m2": round(r.area, 1), "daylit": r.daylit}
                 for r in fp.rooms]
        levels.append({
            "index": i, "name": lv.name, "ffl_m": round(lv.ffl, 3),
            "floor_to_floor_m": round(lv.to_ffl, 3),
            "area_m2": round(lv.area, 1),
            "circulation_m2": round(fp.circulation_area, 1),
            "room_count": len(fp.rooms), "corridors": len(fp.circulation),
            "daylit_m2": round(sum(r.area for r in fp.rooms if r.daylit), 1),
            "internal_m2": round(sum(r.area for r in fp.rooms if not r.daylit), 1),
            "rooms": rooms,
        })
    foot = m.footprint()
    out = {
        "engine": {"name": "archiai", "version": ENGINE_VERSION},
        "project": {
            "name": project.info.get("name"),
            "number": project.info.get("number"),
            "typology": m.name,
            "storeys": len(m.levels),
            "gia_m2": round(m.gia(), 1),
            "footprint_m2": round(foot.area, 1),
            "height_m": round(m.height, 3),
            "bbox_m": [round(v, 3) for v in foot.bbox()],
        },
        "levels": levels,
        "sheets": sheets,
        "totals": {
            "rooms": sum(len(f.rooms) for f in project.floorplans),
            "sheets": len(sheets),
            "cost_units": cost_units(project, sheets),
        },
    }
    source = getattr(project, "source", None)
    if source:
        out["source"] = source
        out["project"]["revision"] = source.get("revision", "P01")
    if spec is not None:
        out["spec"] = {
            "use": spec.use, "shape": spec.shape, "storeys": spec.storeys,
            "area_m2": spec.area, "entrance_azimuth": spec.entrance,
            "floor_to_floor_m": spec.floor_to_floor, "name": spec.name,
        }
        out["assumptions"] = list(spec.assumptions)
    if model:
        out["model"] = model
    return out
