"""Views of the building: pick a camera, pick what to include, get a picture.

This is the deterministic half of rendering. Nothing here is generated by a
model; the picture is the building, drawn with a real camera, a real sun and
the same facade rules the elevations and the window schedule use. Ask for the
same view twice and you get the same image, which is what makes it useful as
a base for a photoreal pass later on.

World axes are the model's: x east, y north, z up.
"""

import math

from . import geom2d as G
from . import openings as OP
from . import buildup as BU


# ---------------------------------------------------------------------------
# Camera
# ---------------------------------------------------------------------------
def _sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def _mul(a, k):
    return (a[0] * k, a[1] * k, a[2] * k)


def _dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def _norm(a):
    m = math.sqrt(_dot(a, a)) or 1.0
    return (a[0] / m, a[1] / m, a[2] / m)


def _newell(pts):
    nx = ny = nz = 0.0
    m = len(pts)
    for i in range(m):
        a, b = pts[i], pts[(i + 1) % m]
        nx += (a[1] - b[1]) * (a[2] + b[2])
        ny += (a[2] - b[2]) * (a[0] + b[0])
        nz += (a[0] - b[0]) * (a[1] + b[1])
    return (nx, ny, nz)


class Camera:
    """Perspective or parallel, looking from `eye` at `target`.

    Everything is done in camera space so the near plane can be clipped
    properly: a face with one corner behind the lens has to be cut, not
    dropped, or a wall vanishes the moment you step close to it."""

    NEAR = 0.35

    def __init__(self, eye, target, fov=48.0, parallel=False, span=None,
                 roll=0.0, width=1600, height=1000):
        self.eye = tuple(float(c) for c in eye)
        self.target = tuple(float(c) for c in target)
        f = _norm(_sub(self.target, self.eye))
        up = (0.0, 0.0, 1.0)
        if abs(_dot(f, up)) > 0.999:
            up = (0.0, 1.0, 0.0)
        r = _norm(_cross(f, up))
        u = _cross(r, f)
        if roll:
            a = math.radians(roll)
            r, u = (_add(_mul(r, math.cos(a)), _mul(u, math.sin(a))),
                    _add(_mul(u, math.cos(a)), _mul(r, -math.sin(a))))
        self.f, self.r, self.u = f, r, u
        self.parallel = parallel
        self.width, self.height = float(width), float(height)
        self.aspect = self.width / self.height
        self.span = span or 60.0
        self.k = (self.height / 2.0) / math.tan(math.radians(fov) / 2.0)
        self.fov = fov

    def to_cam(self, p):
        d = _sub(p, self.eye)
        return (_dot(d, self.r), _dot(d, self.u), _dot(d, self.f))

    def project(self, c):
        """Camera space to pixels. z must already be in front of the lens."""
        if self.parallel:
            s = self.height / self.span
            return (self.width / 2.0 + c[0] * s, self.height / 2.0 - c[1] * s)
        s = self.k / max(c[2], 1e-6)
        return (self.width / 2.0 + c[0] * s, self.height / 2.0 - c[1] * s)

    def clip(self, pts):
        """Sutherland-Hodgman against the near plane, in camera space."""
        if self.parallel:
            return pts
        out = []
        n = len(pts)
        for i in range(n):
            a, b = pts[i], pts[(i + 1) % n]
            ina, inb = a[2] >= self.NEAR, b[2] >= self.NEAR
            if ina:
                out.append(a)
            if ina != inb:
                t = (self.NEAR - a[2]) / (b[2] - a[2])
                out.append((a[0] + (b[0] - a[0]) * t,
                            a[1] + (b[1] - a[1]) * t, self.NEAR))
        return out


# ---------------------------------------------------------------------------
# Sun
# ---------------------------------------------------------------------------
def sun(latitude=51.5, day=172, hour=14.0):
    """Where the sun is, so a shadow means something.

    Day is the day of the year; hour is local solar time. Returns the unit
    vector pointing at the sun, its altitude and its azimuth from north."""
    dec = math.radians(23.45 * math.sin(math.radians(360.0 * (284 + day) / 365.0)))
    lat = math.radians(latitude)
    H = math.radians(15.0 * (hour - 12.0))
    alt = math.asin(math.sin(lat) * math.sin(dec)
                    + math.cos(lat) * math.cos(dec) * math.cos(H))
    az = math.atan2(-math.cos(dec) * math.sin(H),
                    math.sin(dec) * math.cos(lat)
                    - math.cos(dec) * math.sin(lat) * math.cos(H))
    v = (math.cos(alt) * math.sin(az), math.cos(alt) * math.cos(az),
         math.sin(alt))
    return _norm(v), math.degrees(alt), math.degrees(az) % 360.0


# ---------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------
MATERIALS = {
    "glass":    ((150, 178, 194), 0.55),
    # Facades a brief can ask for by name. A monolithic building has to come
    # back looking monolithic, not like a glass box with the word attached.
    "concrete": ((196, 192, 185), 0.03),
    "stone":    ((203, 196, 181), 0.04),
    "brick":    ((166, 122, 104), 0.03),
    "timber":   ((186, 152, 112), 0.05),
    "metal":    ((178, 182, 187), 0.28),
    "mirror":   ((168, 190, 204), 0.72),
    "spandrel": ((176, 180, 184), 0.10),
    "wall":     ((205, 201, 194), 0.06),
    "soffit":   ((168, 165, 159), 0.04),
    "roof":     ((150, 152, 152), 0.04),
    "parapet":  ((188, 190, 191), 0.05),
    "slab":     ((214, 208, 199), 0.04),
    "ground":   ((198, 205, 190), 0.02),
    "paving":   ((208, 206, 200), 0.03),
    "context":  ((196, 194, 190), 0.04),
    "tree":     ((122, 152, 112), 0.02),
    "trunk":    ((122, 106, 88), 0.02),
    "car":      ((168, 172, 178), 0.30),
    "person":   ((70, 74, 80), 0.0),
    "shadow":   ((84, 88, 84), 0.0),
}

STYLES = {
    "material": None,                       # as listed above
    "clay":     (206, 202, 195),
    "white":    (238, 236, 232),
    "line":     None,                       # outlines only
    # Passes. Not pictures to look at: pictures for a machine to read. An
    # image model is conditioned on structure, and these are the structure
    # the engine already knows exactly -- how far away a surface is, which
    # way it faces, and what it is made of. Guessing them back out of a
    # photograph is the hard part everyone else has to do.
    "depth":    None,
    "normal":   None,
    "segment":  None,
}
PASSES = ("depth", "normal", "segment", "line")

# One flat colour per material, far apart from each other so a segmentation
# map can be read back without ambiguity.
SEGMENT = {
    "glass": (60, 120, 200), "spandrel": (120, 90, 190), "wall": (200, 90, 60),
    "concrete": (200, 90, 60), "stone": (210, 110, 70), "brick": (180, 70, 50),
    "timber": (190, 130, 60), "metal": (140, 140, 160), "mirror": (80, 150, 210),
    "soffit": (150, 60, 40), "roof": (230, 170, 40), "parapet": (200, 140, 30),
    "slab": (240, 220, 120), "ground": (70, 160, 70), "paving": (150, 150, 150),
    "context": (110, 110, 130), "tree": (40, 200, 90), "trunk": (90, 70, 40),
    "car": (230, 60, 140), "person": (250, 250, 60), "shadow": (0, 0, 0),
}
SEGMENT_SKY = (18, 18, 24)


def _hex(c):
    return "#%02x%02x%02x" % (max(0, min(255, int(c[0]))),
                              max(0, min(255, int(c[1]))),
                              max(0, min(255, int(c[2]))))


def _shade(base, n, sundir, alt, gloss=0.0, view=None):
    """Sun, sky and a little bounce. Nothing physical, just consistent."""
    day = max(0.0, min(1.0, (alt + 6.0) / 60.0))
    direct = max(0.0, _dot(n, sundir)) * (0.46 * day)
    skyward = 0.5 + 0.5 * n[2]
    ambient = 0.52 + 0.18 * skyward          # sky and bounce, not a black room
    t = min(1.12, ambient + direct)
    warm = (1.0 + 0.06 * direct, 1.0 + 0.02 * direct, 1.0 - 0.04 * direct)
    c = [base[i] * t * warm[i] for i in range(3)]
    if gloss and view is not None:
        h = _norm(_add(sundir, _mul(view, -1.0)))
        spec = max(0.0, _dot(n, h)) ** 24 * gloss * (0.5 + 0.5 * day)
        c = [c[i] + 255.0 * spec for i in range(3)]
        sky = max(0.0, n[2]) * gloss * 0.28
        c = [c[0] + 90 * sky, c[1] + 118 * sky, c[2] + 150 * sky]
    return _hex(c)


# ---------------------------------------------------------------------------
# Scene
# ---------------------------------------------------------------------------
def _bilinear(q, u, v):
    a = _add(_mul(q[0], (1 - u) * (1 - v)), _mul(q[1], u * (1 - v)))
    b = _add(_mul(q[2], u * v), _mul(q[3], (1 - u) * v))
    return _add(a, b)


def _patch(q, u0, v0, u1, v1):
    return [_bilinear(q, u0, v0), _bilinear(q, u1, v0),
            _bilinear(q, u1, v1), _bilinear(q, u0, v1)]


class Scene:
    """Faces in, a sorted picture out. Painter's algorithm, as everywhere."""

    def __init__(self, cam, sundir, alt, style="material"):
        self.cam, self.sun, self.alt = cam, sundir, alt
        self.style = style
        self.items = []

    MAX_FACE = 6.0            # metres; see _emit_face

    def face(self, pts, material, cull=True, stroke=None, w=0.5, flat=None,
             layer=0):
        """Add a face, splitting it if it is large.

        A painter's algorithm orders faces by their average depth, which is
        only right while the faces are small compared with the distances
        between them. One big neighbouring block next to a tall thin building
        is exactly the case where it is not, and the block paints over the
        building it stands behind. Splitting large quads bounds the error
        instead of special-casing it."""
        if len(pts) == 4:
            n = 1
            for i in range(4):
                a, b = pts[i], pts[(i + 1) % 4]
                d = math.sqrt(sum((a[k] - b[k]) ** 2 for k in range(3)))
                n = max(n, int(math.ceil(d / self.MAX_FACE)))
            if n > 1:
                n = min(n, 6)
                for r in range(n):
                    for c in range(n):
                        self._emit_face(_patch(pts, c / n, r / n,
                                               (c + 1) / n, (r + 1) / n),
                                        material, cull, stroke, w, flat, layer,
                                        outline=False)
                if self.style == "line":
                    # the patches carry the occlusion; the real edge is the
                    # edge of the face, drawn once over the top of them
                    self._emit_face(pts, material, cull, "#20242a", 0.7,
                                    "none", layer, outline=True)
                return
        self._emit_face(pts, material, cull, stroke, w, flat, layer)

    def _emit_face(self, pts, material, cull=True, stroke=None, w=0.5,
                   flat=None, layer=0, outline=None):
        cam = self.cam
        cpts = [cam.to_cam(p) for p in pts]
        cpts = cam.clip(cpts)
        if len(cpts) < 3:
            return
        n = _norm(_newell(pts))
        toward = _norm(_sub(pts[0], cam.eye)) if not cam.parallel else cam.f
        if cull and _dot(n, toward) > -0.02:
            return
        xy = [cam.project(c) for c in cpts]
        if not _visible(xy, cam):
            return
        depth = sum(c[2] for c in cpts) / len(cpts)
        fill = self.paint(n, material, toward, depth, flat)
        if self.style == "line" and outline is False:
            stroke, w = None, 0.0          # a patch only occludes
        elif self.style == "line" and stroke is None:
            stroke, w = "#20242a", 0.7
        elif isinstance(fill, tuple):
            stroke, w = None, 0.0          # a pass carries no line work
        elif stroke is None:
            stroke, w = fill, 0.6          # hairline seams between patches
        self.items.append((layer, depth, xy, fill, stroke, w))

    def flat_face(self, pts, fill, stroke=None, w=0.0, layer=-1):
        if self.style in ("depth", "normal", "segment"):
            return                        # a cast shadow is not a surface
        cam = self.cam
        cpts = cam.clip([cam.to_cam(p) for p in pts])
        if len(cpts) < 3:
            return
        xy = [cam.project(c) for c in cpts]
        if not _visible(xy, cam):
            return
        depth = sum(c[2] for c in cpts) / len(cpts)
        self.items.append((layer, depth, xy, fill, stroke, w))

    def paint(self, n, material, toward, depth, flat=None):
        """The colour of one face, whatever the style. Everything that draws a
        surface goes through here; a surface that does not is a hole in the
        pass, and a hole in a control image is worse than no control image."""
        if self.style in ("depth", "normal", "segment"):
            return ("pass", self.style, depth, n, material)
        if flat:
            return flat
        if self.style == "line":
            return "#ffffff"
        base, gloss = MATERIALS.get(material, MATERIALS["wall"])
        if self.style in ("clay", "white"):
            base, gloss = STYLES[self.style], 0.0
        return _shade(base, n, self.sun, self.alt, gloss, toward)

    def _resolve(self, fill):
        """A pass face turned into a colour, once the depth range is known."""
        _tag, style, depth, n, material = fill
        if style == "segment":
            return _hex(SEGMENT.get(material, (128, 128, 128)))
        if style == "normal":
            # camera space, so the encoding means the same thing from any view
            cam = self.cam
            v = (_dot(n, cam.r), _dot(n, cam.u), -_dot(n, cam.f))
            return _hex([(c * 0.5 + 0.5) * 255.0 for c in v])
        lo, hi = self._range
        t = 1.0 - (depth - lo) / max(hi - lo, 1e-6)     # near is bright
        t = max(0.0, min(1.0, t)) ** 0.65               # spread the near field
        return _hex([t * 255.0] * 3)

    def emit(self):
        out = []
        # The ground runs to the horizon. Letting it set the far plane squashes
        # the whole building into the brightest one percent of the range, which
        # is a depth map of a field with a smudge on it.
        depths = [it[1] for it in self.items
                  if isinstance(it[3], tuple) and it[0] > -3]
        if not depths:
            depths = [it[1] for it in self.items if isinstance(it[3], tuple)]
        self._range = (min(depths), max(depths)) if depths else (0.0, 1.0)
        for (layer, depth, geom, fill, stroke, w) in sorted(
                self.items, key=lambda it: (it[0], -it[1])):
            if isinstance(fill, tuple) and fill and fill[0] == "pass":
                fill = self._resolve(fill)
            rule = ""
            if isinstance(geom, tuple) and geom and geom[0] == "evenodd":
                d, rule = geom[1], ' fill-rule="evenodd"'
            else:
                d = "M " + " L ".join("%.2f %.2f" % p for p in geom) + " Z"
            s = '<path d="%s" fill="%s"%s' % (d, fill, rule)
            if stroke:
                s += ' stroke="%s" stroke-width="%.2f" stroke-linejoin="round"' \
                     % (stroke, w)
            out.append(s + "/>")
        return "".join(out)


def _visible(xy, cam, pad=400.0):
    xs = [p[0] for p in xy]
    ys = [p[1] for p in xy]
    return not (max(xs) < -pad or min(xs) > cam.width + pad
                or max(ys) < -pad or min(ys) > cam.height + pad)


def _path(xy, close=True):
    return "M " + " L ".join("%.2f %.2f" % p for p in xy) + (" Z" if close else "")


def _face_with_holes(scene, outer, holes, material):
    """A roof or a slab that has a courtyard in it."""
    cam = scene.cam
    co = cam.clip([cam.to_cam(p) for p in outer])
    if len(co) < 3:
        return
    n = _norm(_newell(outer))
    toward = _norm(_sub(outer[0], cam.eye)) if not cam.parallel else cam.f
    if _dot(n, toward) > -0.02:
        return
    parts = [_path([cam.project(c) for c in co])]
    for h in holes:
        ch = cam.clip([cam.to_cam(p) for p in h])
        if len(ch) >= 3:
            parts.append(_path([cam.project(c) for c in ch]))
    depth = sum(c[2] for c in co) / len(co)
    fill = scene.paint(n, material, toward, depth)
    stroke = "#20242a" if scene.style == "line" else None
    scene.items.append((0, depth, ("evenodd", " ".join(parts)), fill, stroke, 0.7))


# ---------------------------------------------------------------------------
# The building, built from the same rules the drawings use
# ---------------------------------------------------------------------------
def _rings(plate):
    return [(plate.outer, False)] + [(h, True) for h in plate.holes]


def _sample(ring, n):
    """n points spaced equally along a ring, so two rings can be matched up."""
    pts = list(ring)
    m = len(pts)
    seg = [math.dist(pts[i], pts[(i + 1) % m]) for i in range(m)]
    total = sum(seg) or 1.0
    out, i, run = [], 0, 0.0
    for k in range(n):
        want = total * k / n
        while run + seg[i] < want and i < m - 1:
            run += seg[i]
            i += 1
        t = 0.0 if seg[i] < 1e-9 else (want - run) / seg[i]
        a, b = pts[i], pts[(i + 1) % m]
        out.append((a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t))
    return out


def _collar(scene, lower, upper, z, n=64):
    """The horizontal band where one plate steps in or out over another.

    Without it a setback shows the sky through the gap and an overhang has no
    underside. Which it is decides the material: stepping in leaves a terrace,
    stepping out leaves a soffit."""
    a = _sample(lower, n)
    b = _sample(upper, n)
    shrink = abs(G.signed_area(list(upper))) < abs(G.signed_area(list(lower)))
    material = "roof" if shrink else "soffit"
    for k in range(n):
        p0, p1 = a[k], a[(k + 1) % n]
        q0, q1 = b[k], b[(k + 1) % n]
        if (math.dist(p0, q0) < 0.03 and math.dist(p1, q1) < 0.03):
            continue
        quad = [(p0[0], p0[1], z), (p1[0], p1[1], z),
                (q1[0], q1[1], z), (q0[0], q0[1], z)]
        scene.face(quad, material, cull=False)


# Facades the engine can draw, and how much of a storey is window in each.
FACADES = {"glass": ("glass", 1.0), "mirror": ("mirror", 1.0),
           "metal": ("metal", 0.72), "timber": ("timber", 0.55),
           "brick": ("brick", 0.42), "stone": ("stone", 0.42),
           "concrete": ("concrete", 0.42)}


def _facade(project):
    want = (getattr(project.brief, "facade", None) or "glass").strip().lower()
    return FACADES.get(want, FACADES["glass"])


def undercroft(scene, project, keep=None):
    """The open ground plane: what holds the building up, and its soffit.

    A lifted building only reads as lifted if you can see under it, so the
    columns are drawn as shafts and the underside is a lit face rather than
    the bottom edge of a wall."""
    m = project.massing
    keep = keep or (lambda p: True)
    for c in list(m.columns) + list(m.cores):
        ring = G.resample(c.region.outer, 1.5)
        n = len(ring)
        mat = "spandrel" if c.kind == "column" else "wall"
        for k in range(n):
            a, b = ring[k], ring[(k + 1) % n]
            mid = ((a[0] + b[0]) / 2.0, (a[1] + b[1]) / 2.0)
            if not keep(mid):
                continue
            scene.face([(a[0], a[1], 0.0), (b[0], b[1], 0.0),
                        (b[0], b[1], m.lift), (a[0], a[1], m.lift)], mat)
    base = m.levels[0].plate
    _face_with_holes(scene, [(x, y, m.lift) for (x, y) in base.outer][::-1],
                     [[(x, y, m.lift) for (x, y) in h][::-1] for h in base.holes],
                     "soffit")


def building(scene, project, cutaway=None):
    """Facades band by band, so the render shows the windows the schedule
    counts rather than a blank extrusion."""
    m = project.massing
    t = project.brief.wall_t
    top = m.height
    lift = getattr(m, "lift", 0.0)

    def keep(p):
        return cutaway is None or not cutaway(p)

    if lift:
        undercroft(scene, project, keep)

    for i, lv in enumerate(m.levels):
        nxt = m.levels[i + 1].ffl if i + 1 < len(m.levels) else top
        z_sill = lv.ffl + OP.SILL
        z_head = nxt - OP.HEAD_GAP
        base = lv.ffl - OP.HEAD_GAP if i else (lv.ffl if lift else 0.0)
        if i:
            prev = m.levels[i - 1].plate
            _collar(scene, prev.outer, lv.plate.outer, base)
            for k in range(min(len(prev.holes), len(lv.plate.holes))):
                _collar(scene, prev.holes[k], lv.plate.holes[k], base)
        # An opaque facade is mostly solid with a strip of window in it; a
        # glass one is a curtain wall. The brief decides which, so the word
        # "monolithic" changes the picture rather than decorating it.
        solid, band = _facade(project)
        # The facade runs between the plate at this floor and the plate at the
        # next, so a plan that turns or grows gets a ruled surface rather than
        # a vertical extrusion with slots between the floors.
        span = max(1e-6, nxt - lv.ffl)
        for (lower, upper, is_hole) in m.wall_strips(i):
            n = len(lower)
            for k in range(n):
                a0, b0 = lower[k], lower[(k + 1) % n]
                a1, b1 = upper[k], upper[(k + 1) % n]
                mid = ((a0[0] + b0[0]) / 2.0, (a0[1] + b0[1]) / 2.0)
                if not keep(mid):
                    continue
                lo = z_sill + (z_head - z_sill) * (1.0 - band) / 2.0
                hi = z_head - (z_head - z_sill) * (1.0 - band) / 2.0

                def at(p_lo, p_hi, z):
                    t = min(1.0, max(0.0, (z - lv.ffl) / span))
                    return (p_lo[0] + (p_hi[0] - p_lo[0]) * t,
                            p_lo[1] + (p_hi[1] - p_lo[1]) * t, z)

                def strip(z_a, z_b, material):
                    scene.face([at(a0, a1, z_a), at(b0, b1, z_a),
                                at(b0, b1, z_b), at(a0, a1, z_b)], material)

                if lo > base + 0.05:
                    strip(base, lo, solid if solid != "glass"
                          else ("wall" if i == 0 else "spandrel"))
                if hi > lo + 0.05:
                    strip(lo, hi, "glass")
                if z_head > hi + 0.05:
                    strip(hi, z_head,
                          solid if solid != "glass" else "spandrel")
        if i and cutaway is not None:
            _slab(scene, project, i, lv, keep)

    last = m.levels[-1].plate
    _face_with_holes(scene, [(x, y, top) for (x, y) in last.outer],
                     [[(x, y, top) for (x, y) in h] for h in last.holes], "roof")
    par = top + 0.81
    for ring, is_hole in _rings(last):
        pts = G.resample(ring, 3.0)
        n = len(pts)
        for k in range(n):
            a, b = pts[k], pts[(k + 1) % n]
            if not keep(((a[0] + b[0]) / 2.0, (a[1] + b[1]) / 2.0)):
                continue
            scene.face([(a[0], a[1], top - OP.HEAD_GAP),
                        (b[0], b[1], top - OP.HEAD_GAP),
                        (b[0], b[1], par), (a[0], a[1], par)], "parapet")
    _face_with_holes(scene, [(x, y, par) for (x, y) in last.outer],
                     [[(x, y, par) for (x, y) in h] for h in last.holes],
                     "parapet")


def _rgb(hex_str):
    h = (hex_str or "#dddddd").lstrip("#")
    if len(h) != 6:
        return (221, 221, 221)
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _slab(scene, project, i, lv, keep):
    """A cut floor plate.

    The reason to open a building up is to see the plan, so the exposed plate
    is drawn as its rooms in the colours the floor plans use, not as a blank
    tray."""
    for ring, is_hole in _rings(lv.plate):
        pts = G.resample(ring, 3.0)
        n = len(pts)
        for k in range(n):
            a, b = pts[k], pts[(k + 1) % n]
            if keep(((a[0] + b[0]) / 2.0, (a[1] + b[1]) / 2.0)):
                continue
            scene.face([(a[0], a[1], lv.ffl), (b[0], b[1], lv.ffl),
                        (b[0], b[1], lv.ffl - 0.35), (a[0], a[1], lv.ffl - 0.35)],
                       "slab", cull=False)
    _face_with_holes(scene, [(x, y, lv.ffl) for (x, y) in lv.plate.outer],
                     [[(x, y, lv.ffl) for (x, y) in h] for h in lv.plate.holes],
                     "slab")
    fps = getattr(project, "floorplans", None)
    if not fps or i >= len(fps):
        return
    for room in fps[i].rooms:
        base = _rgb(getattr(room, "fill", None))
        if scene.style in ("clay", "white"):
            base = STYLES[scene.style]
        # plan colours are already chosen to be legible; shading them into
        # daylight just washes them out, so they are only knocked back
        fill = ("#ffffff" if scene.style == "line"
                else _hex([c * 0.92 for c in base]))
        scene.face([(x, y, lv.ffl + 0.02) for (x, y) in room.ring], "slab",
                   cull=False, flat=fill,
                   stroke="#9aa0a6" if scene.style != "line" else "#20242a",
                   w=0.35)


# ---------------------------------------------------------------------------
# Shadow
# ---------------------------------------------------------------------------
def shadow_quads(project, sundir, alt):
    """The building's outline dropped onto the ground along the sun.

    Kept separate from the drawing so the geometry can be checked on its own:
    a shadow that falls the wrong way is a bug you want a test to catch, not
    something to squint at in a picture."""
    if alt < 4.0 or sundir[2] < 0.07:
        return []
    m = project.massing

    def drop(p):
        k = p[2] / sundir[2]
        return (p[0] - sundir[0] * k, p[1] - sundir[1] * k, 0.004)

    quads = []
    for i, lv in enumerate(m.levels):
        nxt = m.levels[i + 1].ffl if i + 1 < len(m.levels) else m.height
        for ring, _h in _rings(lv.plate):
            pts = G.resample(ring, 4.0)
            n = len(pts)
            for k in range(n):
                a, b = pts[k], pts[(k + 1) % n]
                quads.append([(a[0], a[1], lv.ffl), (b[0], b[1], lv.ffl),
                              (b[0], b[1], nxt), (a[0], a[1], nxt)])
    last = m.levels[-1].plate
    quads.append([(x, y, m.height + 0.81) for (x, y) in G.resample(last.outer, 4.0)])
    return [[drop(p) for p in q] for q in quads]


def shadows(scene, project, sundir, alt):
    for q in shadow_quads(project, sundir, alt):
        scene.flat_face(q, "#8d938a", layer=-2)


# ---------------------------------------------------------------------------
# Add-ons
# ---------------------------------------------------------------------------
def _radius(project):
    x0, y0, x1, y1 = project.massing.footprint().bbox()
    return max(x1 - x0, y1 - y0) / 2.0


def _wobble(i, salt=0):
    """A repeatable number in 0..1 from an index, so context never changes
    between two renders of the same building."""
    v = (i * 2654435761 + salt * 40503 + 12345) & 0xFFFFFFFF
    v ^= (v >> 13)
    v = (v * 1274126177) & 0xFFFFFFFF
    return ((v >> 8) & 0xFFFF) / 65535.0


def _site(project):
    """Centre, bbox and half-extents of the plate the building sits on."""
    plate = project.massing.footprint()
    x0, y0, x1, y1 = plate.bbox()
    return plate, ((x0 + x1) / 2.0, (y0 + y1) / 2.0), (x0, y0, x1, y1)


def _reach(project, azimuth_deg):
    """How far the building sticks out in one direction, from its centre."""
    plate, (cx, cy), _bb = _site(project)
    a = math.radians(azimuth_deg)
    dx, dy = math.cos(a), math.sin(a)
    return max((p[0] - cx) * dx + (p[1] - cy) * dy for p in plate.outer)


def _pad(project):
    """The paved apron around the building; everything outside stands beyond it."""
    return max(_radius(project) * 0.32, 8.0)


def _ring_points(project, count, offset, phase=0.0, salt=0):
    """Positions spaced around the site, following its shape rather than a
    circle, so a long building does not get its trees bunched at the ends."""
    plate, (cx, cy), (x0, y0, x1, y1) = _site(project)
    hx, hy = (x1 - x0) / 2.0 + offset, (y1 - y0) / 2.0 + offset
    per = 2 * (hx + hy) * 2
    out = []
    for i in range(count):
        t = ((i + phase) / count + 0.02 * _wobble(i, salt)) % 1.0
        s = t * per
        if s < 2 * hx:
            p = (cx - hx + s, cy - hy)
        elif s < 2 * hx + 2 * hy:
            p = (cx + hx, cy - hy + (s - 2 * hx))
        elif s < 4 * hx + 2 * hy:
            p = (cx + hx - (s - 2 * hx - 2 * hy), cy + hy)
        else:
            p = (cx - hx, cy + hy - (s - 4 * hx - 2 * hy))
        if plate.contains(p):
            continue
        out.append(p)
    return out


def ground(scene, project, size=None):
    """The ground, drawn far enough out that its edge is never in frame."""
    cam = scene.cam
    cx, cy = G.centroid(project.massing.footprint().outer)
    reach = math.hypot(cam.eye[0] - cx, cam.eye[1] - cy) + cam.eye[2]
    r = size or max(_radius(project) * 8.0, reach * 14.0)
    scene.face([(cx - r, cy - r, 0.0), (cx + r, cy - r, 0.0),
                (cx + r, cy + r, 0.0), (cx - r, cy + r, 0.0)],
               "ground", cull=False, layer=-3)
    x0, y0, x1, y1 = project.massing.footprint().bbox()
    pad = max(_radius(project) * 0.32, 8.0)
    scene.face([(x0 - pad, y0 - pad, 0.002), (x1 + pad, y0 - pad, 0.002),
                (x1 + pad, y1 + pad, 0.002), (x0 - pad, y1 + pad, 0.002)],
               "paving", cull=False, layer=-3)


def context(scene, project, count=14, seed=0):
    """Neighbouring blocks, placed once and always the same."""
    m = project.massing
    plate, (cx, cy), _bb = _site(project)
    r = _radius(project)
    pad = _pad(project)
    # neighbours sit across a street, and they are neighbours: they read as
    # the setting, so they stay below the building they are the setting for
    street = max(pad * 2.2, m.height * 0.8, 16.0)
    block = max(r * 0.34, 9.0)
    for i, (px, py) in enumerate(_ring_points(project, count,
                                              street + block, 0.5, seed)):
        a = math.atan2(py - cy, px - cx)
        push = block * (0.5 + 1.4 * _wobble(i, seed))
        px, py = px + math.cos(a) * push, py + math.sin(a) * push
        w = block * (0.7 + 0.8 * _wobble(i, seed + 1))
        h = block * (0.6 + 0.8 * _wobble(i, seed + 2))
        z = max(5.0, min(m.height * 0.85,
                         m.height * (0.28 + 0.46 * _wobble(i, seed + 3))))
        ca, sa = math.cos(a), math.sin(a)
        corners = [(-w, -h), (w, -h), (w, h), (-w, h)]
        base = [(px + x * ca - y * sa, py + x * sa + y * ca) for (x, y) in corners]
        if any(plate.contains(p) for p in base):
            continue
        for k in range(4):
            p0, p1 = base[k], base[(k + 1) % 4]
            scene.face([(p0[0], p0[1], 0.0), (p1[0], p1[1], 0.0),
                        (p1[0], p1[1], z), (p0[0], p0[1], z)], "context")
        scene.face([(p[0], p[1], z) for p in base], "context")


def trees(scene, project, count=12, seed=1):
    pad = _pad(project)
    for i, (px, py) in enumerate(_ring_points(project, count, pad * 0.72,
                                              0.35, seed)):
        h = 5.0 + 3.5 * _wobble(i, seed + 6)
        tr = 0.16
        for k in range(4):
            b0 = 2 * math.pi * k / 4
            b1 = 2 * math.pi * (k + 1) / 4
            scene.face([(px + tr * math.cos(b0), py + tr * math.sin(b0), 0.0),
                        (px + tr * math.cos(b1), py + tr * math.sin(b1), 0.0),
                        (px + tr * math.cos(b1), py + tr * math.sin(b1), h * 0.45),
                        (px + tr * math.cos(b0), py + tr * math.sin(b0), h * 0.45)],
                       "trunk", cull=False)
        crown = [(h * 0.10, h * 0.40), (h * 0.28, h * 0.55),
                 (h * 0.30, h * 0.70), (h * 0.20, h * 0.87), (0.0, h)]
        prev = None
        for (rad, z) in crown:
            ring = [(px + rad * math.cos(2 * math.pi * k / 7),
                     py + rad * math.sin(2 * math.pi * k / 7), z) for k in range(7)]
            if prev:
                for k in range(7):
                    scene.face([prev[k], prev[(k + 1) % 7], ring[(k + 1) % 7],
                                ring[k]], "tree", cull=False)
            prev = ring


def cars(scene, project, count=6, seed=2):
    plate, (cx, cy), _bb = _site(project)
    pad = _pad(project)
    for i, (px, py) in enumerate(_ring_points(project, count, pad * 1.06,
                                              0.7, seed)):
        a = math.atan2(py - cy, px - cx)
        ca, sa = math.cos(a + math.pi / 2), math.sin(a + math.pi / 2)
        L, W = 2.30, 0.90
        base = [(px + x * ca - y * sa, py + x * sa + y * ca)
                for (x, y) in ((-L, -W), (L, -W), (L, W), (-L, W))]
        for (z0, z1, inset) in ((0.20, 0.80, 0.0), (0.80, 1.42, 0.35)):
            ring = base
            if inset:
                ring = [(px + (p[0] - px) * (1 - inset), py + (p[1] - py) * (1 - inset))
                        for p in base]
            for k in range(4):
                p0, p1 = ring[k], ring[(k + 1) % 4]
                scene.face([(p0[0], p0[1], z0), (p1[0], p1[1], z0),
                            (p1[0], p1[1], z1), (p0[0], p0[1], z1)], "car")
            scene.face([(p[0], p[1], z1) for p in ring], "car")


def people(scene, project, count=9, seed=4):
    """Figures placed on the ground, drawn facing the camera."""
    cam = scene.cam
    plate, (cx, cy), _bb = _site(project)
    pad = _pad(project)
    az = project.brief.entrance_azimuth
    for i in range(count):
        a = math.radians(az + (_wobble(i, seed) - 0.5) * 150.0)
        d = _reach(project, math.degrees(a)) + pad * (0.20 + 0.62 * _wobble(i, seed + 7))
        px, py = cx + math.cos(a) * d, cy + math.sin(a) * d
        if plate.contains((px, py)):
            continue
        h = 1.62 + 0.16 * _wobble(i, seed + 8)
        foot, head = cam.to_cam((px, py, 0.0)), cam.to_cam((px, py, h))
        if min(foot[2], head[2]) < cam.NEAR:
            continue
        f2, h2 = cam.project(foot), cam.project(head)
        ph = f2[1] - h2[1]
        if ph < 3.0 or ph > cam.height * 1.4:
            continue
        w = ph * 0.20
        sh = h2[1] + ph * 0.17                      # shoulder line
        body = [(f2[0] - w * 0.30, f2[1]),
                (f2[0] - w * 0.16, f2[1] - ph * 0.42),
                (f2[0] - w * 0.50, sh + ph * 0.06),
                (f2[0] - w * 0.34, sh),
                (f2[0] + w * 0.34, sh),
                (f2[0] + w * 0.50, sh + ph * 0.06),
                (f2[0] + w * 0.16, f2[1] - ph * 0.42),
                (f2[0] + w * 0.30, f2[1])]
        facing = _mul(cam.f, -1.0)
        fill = scene.paint(facing, "person", cam.f, foot[2], flat="#4b5058")
        scene.items.append((1, foot[2], body, fill, None, 0.0))
        hr = ph * 0.075
        hy = h2[1] + hr
        head = [(f2[0] + hr * math.cos(2 * math.pi * k / 10),
                 hy + hr * math.sin(2 * math.pi * k / 10)) for k in range(10)]
        scene.items.append((1, foot[2] - 0.01, head, fill, None, 0.0))


# ---------------------------------------------------------------------------
# Named cameras, worked out from the model
# ---------------------------------------------------------------------------
NAMED = ("aerial-ne", "aerial-nw", "aerial-se", "aerial-sw", "aerial",
         "eye-north", "eye-south", "eye-east", "eye-west",
         "entrance", "courtyard", "roof", "axo", "worm")

_AZ = {"north": 90.0, "south": 270.0, "east": 0.0, "west": 180.0,
       "ne": 45.0, "nw": 135.0, "se": 315.0, "sw": 225.0}


def _frame_distance(project, az, eye_z, fov, aspect, margin=0.84):
    """How far back to stand so the whole building is in the frame.

    Framing from the model rather than a fixed multiple means the same named
    view works for a two storey pavilion and a forty storey tower."""
    m = project.massing
    reach = _reach(project, az)
    across = max(_reach(project, az + 90.0), _reach(project, az - 90.0))
    vt = math.tan(math.radians(fov) / 2.0) * margin
    ht = vt * aspect
    need_up = (m.height + 1.2 - eye_z) / max(vt, 1e-3)
    need_down = eye_z / max(vt, 1e-3)
    need_side = across / max(ht, 1e-3)
    return reach + max(need_up, need_down, need_side, 6.0)


def camera(project, name="aerial-ne", width=1600, height=1000, fov=48.0,
           azimuth=None, elevation=None, distance=None, eye_height=None):
    """A camera for a named view, sized to the building it is looking at.

    Every named view is derived from the model: the distance comes from how
    big the building is, so the same name frames a kiosk and a tower equally
    well. Any part of it can be overridden."""
    m = project.massing
    plate = m.footprint()
    x0, y0, x1, y1 = plate.bbox()
    cx, cy = (x0 + x1) / 2.0, (y0 + y1) / 2.0
    r = max(max(x1 - x0, y1 - y0) / 2.0, m.height * 0.6, 6.0)
    name = (name or "aerial-ne").lower()

    if name == "roof":
        span = max(x1 - x0, y1 - y0) * 1.25
        return Camera((cx, cy - 0.001, m.height + r * 3.0), (cx, cy, m.height),
                      parallel=True, span=span, width=width, height=height)
    if name == "axo":
        az = math.radians(azimuth if azimuth is not None else 235.0)
        el = math.radians(elevation if elevation is not None else 30.0)
        d = distance or r * 6.0
        eye = (cx + math.cos(az) * math.cos(el) * d,
               cy + math.sin(az) * math.cos(el) * d,
               m.height * 0.4 + math.sin(el) * d)
        span = max(x1 - x0, y1 - y0, m.height * 1.6) * 1.5
        return Camera(eye, (cx, cy, m.height * 0.38), parallel=True, span=span,
                      width=width, height=height)

    if name == "courtyard":
        holes = plate.holes
        if holes:
            # Stand at the bottom of the void and look up it. A void that
            # opens as it rises is only legible from underneath, and the eye
            # has to stay inside the narrowest floor or it ends up in a wall.
            h = max(holes, key=lambda k: abs(G.signed_area(k)))
            hx, hy = G.centroid(h)
            hb = G.Region(h).bbox()
            near = min(hb[2] - hb[0], hb[3] - hb[1])
            a = math.radians(azimuth if azimuth is not None else 225.0)
            back = near * 0.30
            eye = (hx - math.cos(a) * back, hy - math.sin(a) * back,
                   eye_height or 1.62)
            if not G.point_in_ring((eye[0], eye[1]), h):
                eye = (hx, hy, eye_height or 1.62)
            return Camera(eye, (hx + math.cos(a) * back * 0.5,
                                hy + math.sin(a) * back * 0.5,
                                m.height * 1.02),
                          fov=max(fov, 62.0), width=width, height=height)
        name = "entrance"

    def stand_off(az, extra):
        """Far enough out to see the whole thing, and clear of the trees."""
        return _reach(project, az) + _pad(project) * 1.9 + extra

    aspect = float(width) / float(height)

    if name == "entrance":
        az = azimuth if azimuth is not None else project.brief.entrance_azimuth
        ez = eye_height or 1.65
        d = distance or max(stand_off(az, 0.0),
                            _frame_distance(project, az, ez, fov, aspect, 0.78))
        a = math.radians(az)
        eye = (cx + math.cos(a) * d, cy + math.sin(a) * d, ez)
        return Camera(eye, (cx, cy, m.height * 0.42), fov=fov, width=width,
                      height=height)

    if name == "worm":
        az = azimuth if azimuth is not None else 225.0
        d = distance or _reach(project, az) + _pad(project) * 0.5
        a = math.radians(az)
        eye = (cx + math.cos(a) * d, cy + math.sin(a) * d, eye_height or 1.30)
        return Camera(eye, (cx, cy, m.height * 0.95), fov=fov + 14.0,
                      width=width, height=height)

    if name.startswith("eye"):
        key = name.split("-")[-1]
        az = azimuth if azimuth is not None else _AZ.get(key, 270.0)
        ez = eye_height or 1.65
        d = distance or max(stand_off(az, 0.0),
                            _frame_distance(project, az, ez, fov, aspect))
        a = math.radians(az)
        eye = (cx + math.cos(a) * d, cy + math.sin(a) * d, ez)
        return Camera(eye, (cx, cy, m.height * 0.45), fov=fov, width=width,
                      height=height)

    key = name.split("-")[-1] if "-" in name else "ne"
    az = azimuth if azimuth is not None else _AZ.get(key, 45.0)
    el = elevation if elevation is not None else 26.0
    ez = max(m.height * 0.5, math.sin(math.radians(el)) *
             _frame_distance(project, az, m.height * 0.5, fov, aspect, 0.80))
    d = distance or _frame_distance(project, az, ez, fov, aspect, 0.80) \
        + _pad(project)
    a, e = math.radians(az), math.radians(el)
    eye = (cx + math.cos(a) * math.cos(e) * d, cy + math.sin(a) * math.cos(e) * d,
           max(m.height * 0.55, math.sin(e) * d))
    return Camera(eye, (cx, cy, m.height * 0.42), fov=fov, width=width,
                  height=height)


# ---------------------------------------------------------------------------
# Putting one together
# ---------------------------------------------------------------------------
ADDONS = ("ground", "sky", "shadow", "context", "trees", "cars", "people",
          "cutaway")
DEFAULT_ADDONS = ("ground", "sky", "shadow")

SKY = {"day": ("#cfe0ec", "#eef3f5"), "clear": ("#a8c8e2", "#e6eef3"),
       "overcast": ("#d7dade", "#eeeff1"), "evening": ("#e7c9ad", "#f4e6d8"),
       "none": None}


def _sky_svg(cam, kind, ground_line=None):
    pair = SKY.get(kind, SKY["day"])
    if not pair:
        return '<rect width="%.0f" height="%.0f" fill="#ffffff"/>' % (
            cam.width, cam.height)
    return ('<defs><linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">'
            '<stop offset="0" stop-color="%s"/><stop offset="1" stop-color="%s"/>'
            '</linearGradient></defs>'
            '<rect width="%.0f" height="%.0f" fill="url(#sky)"/>'
            % (pair[0], pair[1], cam.width, cam.height))


def render(project, name="aerial-ne", style="material", addons=None,
           width=1600, height=1000, latitude=51.5, day=172, hour=14.0,
           sky="day", fov=48.0, azimuth=None, elevation=None, distance=None,
           eye_height=None, cut_azimuth=45.0):
    """One view of the building, as a self-contained SVG string."""
    if style not in STYLES:
        raise ValueError("style must be one of %s" % ", ".join(sorted(STYLES)))
    if name not in NAMED and azimuth is None:
        raise ValueError("view must be one of %s, or give an azimuth"
                         % ", ".join(NAMED))
    want = set(addons if addons is not None else DEFAULT_ADDONS)
    unknown = want - set(ADDONS)
    if unknown:
        raise ValueError("unknown add-on(s): %s" % ", ".join(sorted(unknown)))

    cam = camera(project, name, width, height, fov, azimuth, elevation,
                 distance, eye_height)
    sundir, alt, sunaz = sun(latitude, day, hour)
    sc = Scene(cam, sundir, alt, style)

    if "ground" in want:
        ground(sc, project)
    if "context" in want:
        context(sc, project)
    if "shadow" in want:
        shadows(sc, project, sundir, alt)

    cut = None
    if "cutaway" in want:
        # a quadrant, not a half: opening ninety degrees shows the plates and
        # still leaves three sides of envelope standing
        cx, cy = G.centroid(project.massing.footprint().outer)
        a1 = math.radians(cut_azimuth - 45.0)
        a2 = math.radians(cut_azimuth + 45.0)
        n1 = (math.cos(a1), math.sin(a1))
        n2 = (math.cos(a2), math.sin(a2))

        def cut(p):
            dx, dy = p[0] - cx, p[1] - cy
            return (dx * n1[0] + dy * n1[1] > 0.0
                    and dx * n2[0] + dy * n2[1] > 0.0)

    building(sc, project, cutaway=cut)

    if "trees" in want:
        trees(sc, project)
    if "cars" in want:
        cars(sc, project)
    if "people" in want:
        people(sc, project)

    body = sc.emit()
    if style in PASSES:
        back = {"depth": "#000000", "normal": "#7f7fff",
                "segment": _hex(SEGMENT_SKY), "line": "#ffffff"}[style]
        head = '<rect width="%.0f" height="%.0f" fill="%s"/>' % (
            cam.width, cam.height, back)
    else:
        head = _sky_svg(cam, sky)
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" '
            'viewBox="0 0 %d %d">%s%s</svg>'
            % (int(width), int(height), int(width), int(height), head, body))


def describe(project, name="aerial-ne", latitude=51.5, day=172, hour=14.0):
    """What a view is actually of, for the caller's records."""
    cam = camera(project, name)
    sundir, alt, az = sun(latitude, day, hour)
    return {"view": name,
            "eye_m": [round(c, 2) for c in cam.eye],
            "target_m": [round(c, 2) for c in cam.target],
            "projection": "parallel" if cam.parallel else "perspective",
            "field_of_view_deg": None if cam.parallel else round(cam.fov, 1),
            "sun": {"latitude": latitude, "day_of_year": day, "hour": hour,
                    "altitude_deg": round(alt, 1), "azimuth_deg": round(az, 1)}}
